import { SpotData } from './types';

export const sampleData: SpotData[] = [
  {
    research_id: 'trip_01',
    research_name: 'Research Trip 01',
    spot_order: 1,
    spot_name: 'Dalian',
    lat: 38.914,
    lng: 121.6147,
    date_start: '2024-03-15',
    date_end: '2024-03-17',
    title: 'Spot Title Here',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    thumbnail_url: 'https://picsum.photos/seed/dalian/400/300',
    image_urls: [
      'https://picsum.photos/seed/dalian1/800/600',
      'https://picsum.photos/seed/dalian2/800/600',
      'https://picsum.photos/seed/dalian3/800/600',
    ],
    video_url: '',
    color: '#2563eb',
  },
  {
    research_id: 'trip_01',
    research_name: 'Research Trip 01',
    spot_order: 2,
    spot_name: 'Dandong',
    lat: 40.1164,
    lng: 124.3946,
    date_start: '2024-03-18',
    date_end: '2024-03-18',
    title: 'Spot Title Here',
    description:
      'Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    thumbnail_url: 'https://picsum.photos/seed/dandong/400/300',
    image_urls: [
      'https://picsum.photos/seed/dandong1/800/600',
      'https://picsum.photos/seed/dandong2/800/600',
    ],
    video_url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    color: '#2563eb',
  },
  {
    research_id: 'trip_01',
    research_name: 'Research Trip 01',
    spot_order: 3,
    spot_name: 'Yanbian',
    lat: 42.8916,
    lng: 129.5089,
    date_start: '2024-03-19',
    date_end: '2024-03-22',
    title: 'Spot Title Here',
    description:
      'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
    thumbnail_url: 'https://picsum.photos/seed/yanbian/400/300',
    image_urls: [
      'https://picsum.photos/seed/yanbian1/800/600',
      'https://picsum.photos/seed/yanbian2/800/600',
      'https://picsum.photos/seed/yanbian3/800/600',
      'https://picsum.photos/seed/yanbian4/800/600',
    ],
    video_url: '',
    color: '#2563eb',
  },
  {
    research_id: 'trip_02',
    research_name: 'Research Trip 02',
    spot_order: 1,
    spot_name: 'Nagasaki',
    lat: 32.7503,
    lng: 129.8779,
    date_start: '2024-06-10',
    date_end: '2024-06-13',
    title: 'Spot Title Here',
    description:
      'Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    thumbnail_url: 'https://picsum.photos/seed/nagasaki/400/300',
    image_urls: [
      'https://picsum.photos/seed/nagasaki1/800/600',
      'https://picsum.photos/seed/nagasaki2/800/600',
    ],
    video_url: '',
    color: '#16a34a',
  },
  {
    research_id: 'trip_02',
    research_name: 'Research Trip 02',
    spot_order: 2,
    spot_name: 'Hiroshima',
    lat: 34.3853,
    lng: 132.4553,
    date_start: '2024-06-14',
    date_end: '2024-06-14',
    title: 'Spot Title Here',
    description:
      'Curabitur pretium tincidunt lacus. Nulla gravida orci a odio. Nullam varius, turpis et commodo pharetra.',
    thumbnail_url: 'https://picsum.photos/seed/hiroshima/400/300',
    image_urls: [
      'https://picsum.photos/seed/hiroshima1/800/600',
      'https://picsum.photos/seed/hiroshima2/800/600',
      'https://picsum.photos/seed/hiroshima3/800/600',
    ],
    video_url: '',
    color: '#16a34a',
  },
  {
    research_id: 'trip_03',
    research_name: 'Research Trip 03',
    spot_order: 1,
    spot_name: 'Berlin',
    lat: 52.52,
    lng: 13.405,
    date_start: '2024-09-01',
    date_end: '2024-09-05',
    title: 'Spot Title Here',
    description:
      'Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.',
    thumbnail_url: 'https://picsum.photos/seed/berlin/400/300',
    image_urls: [
      'https://picsum.photos/seed/berlin1/800/600',
      'https://picsum.photos/seed/berlin2/800/600',
    ],
    video_url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    color: '#d946ef',
  },
  {
    research_id: 'trip_03',
    research_name: 'Research Trip 03',
    spot_order: 2,
    spot_name: 'Amsterdam',
    lat: 52.3676,
    lng: 4.9041,
    date_start: '2024-09-07',
    date_end: '2024-09-10',
    title: 'Spot Title Here',
    description:
      'Maecenas faucibus mollis interdum. Donec sed odio dui. Praesent commodo cursus magna, vel scelerisque nisl consectetur et.',
    thumbnail_url: 'https://picsum.photos/seed/amsterdam/400/300',
    image_urls: [
      'https://picsum.photos/seed/amsterdam1/800/600',
      'https://picsum.photos/seed/amsterdam2/800/600',
      'https://picsum.photos/seed/amsterdam3/800/600',
    ],
    video_url: '',
    color: '#d946ef',
  },
];
